apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-concierge-operator
  namespace: db-concierge
  labels:
    app.kubernetes.io/name: db-concierge-operator
    app.kubernetes.io/component: operator

