apiVersion: v1
kind: Service
metadata:
  name: chartmuseum
  namespace: chartmuseum
  labels:
    app.kubernetes.io/name: chartmuseum
    app.kubernetes.io/part-of: percona-operator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chartmuseum
  ports:
    - name: http
      port: 80
      targetPort: 8080

